appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default, win: azure}
travis:
  secure: {BINSTAR_TOKEN: DABUSUeVP0Mz/ODIqloKileHYMu02Fuo0e11QAh6CkZOGfhEx1vDCoAg4k1eLd7rUZxX6SvxiLvewpJxZEQvgv1ID1x16VMEdKJqCTT8/uCKCPElB3MGZhQAibTfCT2Q6gaFIWF3+TSR4tU36kmoxN95/l9E6dDVoMuS7xHsV1uXE9e6A69AoNbCX9HekVQGWPWu6xGOW4dQIl+ll5XD7uDhu62Ye/vkYowQqgmmsW4G2MXcuu1yyurKQcoo4q4o3gO+HF6ruVXIrGAmvDKnyDMhmj4dQqR1nUdkHbn+KKJVYUpVnOPLNHRATOW2ehZvn5sBK/1BSjsKu+AQMgfaMrbbO+t2Z29oYOej0QSxjWdRCvvQPSZpEOTAWKVzVTbE4YeDC8xGRpHHsnBwn8tpDKnw99DAHtxVgo7MTNQvyJB2UeP50ZMce2p8FJHTQQABAnnjb0u9CqNjcU8PuSTZrrF2agvdprD5gkHanLhaQNmOs/btxBD5A2XlUVeIGgEKByi/6lAVt4ux5Eh9XMA9s1RSXQOZ12Z2tGXRXNW9Mv6JoPQ5Uw7OTF1U+sSkY20wnjiq+pQKMt09WaDqhanY2cNRKmzq3sYcF2dXe5T8fwQfMk7SQc0vbumNmHAG3xBcg0205TOKCUiIKPb0shCwTufiqhVJ9xuih8hdlhMHWmE=}
bot:
  automerge: true
